import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon/favicon.ico',
    apple: '/icon/apple-touch-icon.png',
    shortcut: '/icon/android-chrome-512x512.png',
  },
}
